[config]
reload_apps = true

[config.wallpaper]
command = "awww"
arguments = [ "img", "-t", "fade", "--transition-duration", "0.5", "--transition-step", "255", "--transition-fps", "60", "-f", "Nearest",]
set = true
[templates.hyprland]
input_path = "~/.config/Ax-Shell/config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/Ax-Shell/config/hypr/colors.conf"
[templates.waybar]                                                                                                                                                             
input_path = "~/.config/Ax-Shell/config/matugen/templates/waybar.css"                                                                                                            
output_path = "~/.config/waybar/style.css"
[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'
[templates.swaync]                                                                                                                                                             
input_path = "~/.config/Ax-Shell/config/matugen/templates/swaync.css"                                                                                                            
output_path = "~/.config/swaync/style.css"
post_hook = 'swaync-client -rs'
[templates.fish]
input_path = "./templates/fish.txt"
output_path = "/home/duarte/.local/state/caelestia/sequences.txt"
[templates.qt6ct]
input_path = "./templates/qt6ct.conf"
output_path = "/home/duarte/.config/qt6ct/colors/matugen.conf"
#Delete the gtk3 and gtk4 config files for this to work 
[templates.gtk4]
input_path = "./templates/gtk.css"
output_path = "/home/duarte/.config/gtk-4.0/gtk.css"
[templates.gtk3]
input_path = "./templates/gtk.css"
output_path = "/home/duarte/.config/gtk-3.0/gtk.css"


[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
