$wallpaper = /home/duarte/Pictures/Wallpapers/code_geass/cc_zero.png
$background = 12140e
$foreground = e3e3d9

$primary = dafaa1
$secondary = bfcca3
$tertiary = b1ffd2
$surface = 12140e
$surface_bright = 383a33
$outline = 8f9283
$error = 000000

$shadow = 000000

$red = ffb595
$green = ebffd5
$yellow = ffffff
$blue = afc6ff
$magenta = ffafd6
$cyan = ffffff
$white = ffffff
$red_dim = 000000
$green_dim = 000000
$yellow_dim = 000000
$blue_dim = 000000
$magenta_dim = 000000
$cyan_dim = 000000
