$wallpaper = /home/duarte/Pictures/Wallpapers/scenery/Fantasy-Snow-Valley.png
$background = 111318
$foreground = e2e2e8

$primary = a6c8ff
$secondary = b6c7e6
$tertiary = edb1fe
$surface = 111318
$surface_bright = 393b40
$outline = 8c919b
$error = 000000

$shadow = 000000

$red = ffb2b9
$green = e8ffea
$yellow = ffffff
$blue = b3c5ff
$magenta = eab2ff
$cyan = ffffff
$white = ffffff
$red_dim = 000000
$green_dim = 000000
$yellow_dim = 000000
$blue_dim = 000000
$magenta_dim = 000000
$cyan_dim = 000000
