$wallpaper = /home/duarte/Pictures/Wallpapers/patters/a_blue_and_pink_swirls_on_a_black_background.png
$background = 121316
$foreground = e3e2e5

$primary = a8c9f3
$secondary = bbc7da
$tertiary = e4b8e7
$surface = 121316
$surface_bright = 3a3b3e
$outline = 8d9199
$error = 000000

$shadow = 000000

$red = ffb2b9
$green = e8ffea
$yellow = ffffff
$blue = afc6ff
$magenta = eab2ff
$cyan = ffffff
$white = ffffff
$red_dim = 000000
$green_dim = 000000
$yellow_dim = 000000
$blue_dim = 000000
$magenta_dim = 000000
$cyan_dim = 000000
