shell=fish
title=foot
font=JetBrains Mono Nerd Font:size=12
letter-spacing=0
dpi-aware=no
pad=25x25
bold-text-in-bright=no
gamma-correct-blending=no

[scrollback]
lines=10000

[cursor]
style=beam
beam-thickness=1.5

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
search-start=Control+Shift+f

[search-bindings]
cancel=Escape
find-prev=Shift+F3
find-next=F3 Control+G

[colors-dark]
foreground=e6e1e7
alpha=0.8
selection-foreground=ffffff

cursor=141317 cfbcff

# Normal ANSI
regular0=352165
regular1=ffb4ab
regular2=ff7acd
regular3=ccc1e4
regular4=cfbcff
regular5=ffade0
regular6=ccc1e4
regular7=e6e1e7

# Bright ANSI
bright0=808080
bright1=ffb4ab
bright2=ffade0
bright3=ccc1e4
bright4=cfbcff
bright5=ffade0
bright6=ccc1e4

dim-blend-towards=black