shell=fish
title=foot
font=JetBrains Mono Nerd Font:size=12
letter-spacing=0
dpi-aware=no
pad=25x25
bold-text-in-bright=no
gamma-correct-blending=no

[scrollback]
lines=10000

[cursor]
style=beam
beam-thickness=1.5

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
search-start=Control+Shift+f

[search-bindings]
cancel=Escape
find-prev=Shift+F3
find-next=F3 Control+G

[colors-dark]
foreground=e3e1eb
alpha=0.8
selection-foreground=ffffff

cursor=12131a bbc3ff

# Normal ANSI
regular0=001a93
regular1=ffb4ab
regular2=ff76ff
regular3=bec3f6
regular4=bbc3ff
regular5=ffa9ff
regular6=bec3f6
regular7=e3e1eb

# Bright ANSI
bright0=808080
bright1=ffb4ab
bright2=ffa9ff
bright3=bec3f6
bright4=bbc3ff
bright5=ffa9ff
bright6=bec3f6

dim-blend-towards=black