shell=fish
title=foot
font=JetBrains Mono Nerd Font:size=12
letter-spacing=0
dpi-aware=no
pad=25x25
bold-text-in-bright=no
gamma-correct-blending=no

[scrollback]
lines=10000

[cursor]
style=beam
beam-thickness=1.5

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
search-start=Control+Shift+f

[search-bindings]
cancel=Escape
find-prev=Shift+F3
find-next=F3 Control+G

[colors-dark]
foreground=eae1db
alpha=0.8
selection-foreground=000000

cursor=16130f eebe8a

# Normal ANSI
regular0=452802
regular1=ffb4ab
regular2=b3bb6e
regular3=dcc2a9
regular4=eebe8a
regular5=c5cb91
regular6=dcc2a9
regular7=eae1db

# Bright ANSI
bright0=808080
bright1=ffb4ab
bright2=c5cb91
bright3=dcc2a9
bright4=eebe8a
bright5=c5cb91
bright6=dcc2a9

dim-blend-towards=black